## Makefile for an adv3Lite library game template

-D LANGUAGE=swedish
-D __DEBUG
-Fy obj
-Fo obj
-FI /usr/local/share/frobtads/tads3/include
-FL /usr/local/share/frobtads/tads3/lib

-v
-d
-o ovning13.t3

##sources
-source reflect
-lib system
-lib adv3Lite/adv3Lite

-source adv3Lite/extensions/postures
-source adv3Lite/swedish/swe_postures
-source ovning13



