## Makefile for an adv3Lite library game template

-I liblite
-D LANGUAGE=swedish
-D DEBUG__
-D __DEBUG
-Fy obj
-Fo obj
-FI /usr/local/share/frobtads/tads3/include
-FL /usr/local/share/frobtads/tads3/lib
#-we
-v
-d
-o game.t3

##sources
-source reflect
-lib system
-lib adv3Lite/adv3Lite

-source adv3Lite/extensions/postures
-source adv3Lite/swedish/swe_postures
-source gameMain

-res
GameInfo.txt


