## Makefile for an adv3Lite library game template

-D LANGUAGE=swedish
-D __DEBUG
-Fy obj
-Fo obj
-FI /usr/local/share/frobtads/tads3/include
-FL /usr/local/share/frobtads/tads3/lib
-v
-d
-o tester.t3

##sources
-lib system
-lib adv3Lite/adv3Lite
-source testunit

-source present-tense
#-source vocab-tests

-res
GameInfo.txt


