-pre
-D LANGUAGE=swedish
-Fy obj
-Fo obj
-FI /usr/local/share/frobtads/tads3/include
-FL /usr/local/share/frobtads/tads3/lib
-v
-w1
-D __DEBUG
-d
-o flygplats.t3

##sources
-source reflect
-lib system
-lib adv3Lite/adv3Lite

-source adv3Lite/extensions/postures
-source adv3Lite/swedish/swe_postures

-source start
-source gatearea
-source plane
-source npcs


